services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules # Ignore les node_modules locaux
    stdin_open: true
    tty: true
