# Étape 1 : Utiliser une image Node.js officielle
FROM node:18

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier tout le code source dans le conteneur
COPY . .

# Étape 6 : Exposer le port de développement de Vite
EXPOSE 5173

# Étape 7 : Commande pour démarrer le mode dev
CMD ["npm", "run", "dev"]
